-- 코드를 입력하세요

# SELECT DATETIME
# FROM ANIMAL_OUTS
# ORDER BY DATETIME;

SELECT SUBSTR(DATETIME, 12,2) HOUR, COUNT(DATETIME) COUNT
FROM ANIMAL_OUTS
GROUP BY SUBSTR(DATETIME, 12,2)
HAVING HOUR >= 9 AND HOUR <20
ORDER BY HOUR ASC;