-- 코드를 입력하세요

# SELECT *
# FROM USED_GOODS_REPLY;

SELECT B.TITLE, B.BOARD_ID,R.REPLY_ID,R.WRITER_ID,R.CONTENTS,SUBSTR(R.CREATED_DATE, 1,10) AS CREATED_DATE
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE SUBSTR(B.CREATED_DATE, 6,2) = '10'
ORDER BY R.CREATED_DATE , B.TITLE;