-- 코드를 입력하세요

SELECT CATEGORY, MAX(PRICE) MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT 
WHERE CATEGORY IN ('식용유','과자','국','김치') AND PRICE = ANY(
SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY)
GROUP BY CATEGORY, PRODUCT_NAME
ORDER BY PRICE DESC;